// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	todo "github.com/anthonymartz17/Go-CLI-TODO.git/internal/entity/todo"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Load provides a mock function with no fields
func (_m *Store) Load() ([]*todo.Todo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []*todo.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*todo.Todo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*todo.Todo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*todo.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: payload
func (_m *Store) Save(payload []*todo.Todo) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*todo.Todo) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
