// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	todo "github.com/anthonymartz17/Go-CLI-TODO.git/internal/entity/todo"
	mock "github.com/stretchr/testify/mock"
)

// TodoRepo is an autogenerated mock type for the TodoRepo type
type TodoRepo struct {
	mock.Mock
}

// DeleteTask provides a mock function with given fields: taskId
func (_m *TodoRepo) DeleteTask(taskId string) error {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetList provides a mock function with no fields
func (_m *TodoRepo) GetList() ([]*todo.Todo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []*todo.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*todo.Todo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*todo.Todo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*todo.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveTask provides a mock function with given fields: task
func (_m *TodoRepo) SaveTask(task *todo.Todo) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for SaveTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*todo.Todo) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleDone provides a mock function with given fields: taskId
func (_m *TodoRepo) ToggleDone(taskId string) error {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for ToggleDone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTask provides a mock function with given fields: taskId, task
func (_m *TodoRepo) UpdateTask(taskId string, task string) error {
	ret := _m.Called(taskId, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(taskId, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoRepo creates a new instance of TodoRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoRepo {
	mock := &TodoRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
