// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TodoController is an autogenerated mock type for the TodoController type
type TodoController struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: task
func (_m *TodoController) AddTask(task string) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleDelete provides a mock function with given fields: taskId
func (_m *TodoController) HandleDelete(taskId string) error {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for HandleDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PrintList provides a mock function with no fields
func (_m *TodoController) PrintList() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrintList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleDone provides a mock function with given fields: taskId
func (_m *TodoController) ToggleDone(taskId string) error {
	ret := _m.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for ToggleDone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(taskId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTask provides a mock function with given fields: taskId, task
func (_m *TodoController) UpdateTask(taskId string, task string) error {
	ret := _m.Called(taskId, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(taskId, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoController creates a new instance of TodoController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoController(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoController {
	mock := &TodoController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
