// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TodoHandler is an autogenerated mock type for the TodoHandler type
type TodoHandler struct {
	mock.Mock
}

// HandleAdd provides a mock function with given fields: fields
func (_m *TodoHandler) HandleAdd(fields []string) error {
	ret := _m.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for HandleAdd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleDelete provides a mock function with given fields: fields
func (_m *TodoHandler) HandleDelete(fields []string) error {
	ret := _m.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for HandleDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleDone provides a mock function with given fields: fields
func (_m *TodoHandler) HandleDone(fields []string) error {
	ret := _m.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for HandleDone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleList provides a mock function with no fields
func (_m *TodoHandler) HandleList() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HandleList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleUpdate provides a mock function with given fields: fields
func (_m *TodoHandler) HandleUpdate(fields []string) error {
	ret := _m.Called(fields)

	if len(ret) == 0 {
		panic("no return value specified for HandleUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoHandler creates a new instance of TodoHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoHandler {
	mock := &TodoHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
